import type { Metadata } from "next";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import Navbar from "@/components/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let isAuthed = false;
  try {
    const supabase = getSupabaseServerClient();
    const { data } = await supabase.auth.getSession();
    isAuthed = Boolean(data.session);
  } catch {
    isAuthed = false;
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isAuthed && <Navbar />}
        {children}
      </body>
    </html>
  );
}
